name: temoa-stoch-py3
channels:
    - defaults
    - conda-forge
dependencies:
    - python>=2.7.0
    - xlwt
    - ipython
    - matplotlib
    - pandas
    - numpy
    - scipy
    - joblib
    - salib
    - pydoe
    - pyutilib
    - glpk
    - coincbc