name: temoa-py3
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7.3
    - pyomo=5.5
    - pyomo.extras
    - xlwt
    - ipython
    - matplotlib
    - pandas
    - numpy
    - scipy
    - joblib
    - salib
    - pydoe
    - pyutilib
    - glpk
    - coincbc